###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  attai:
    disabled: false
    displayname: 'Attai'
    password: 'dasisteintest'
    email: 'amadeus@mozart409.com'
    groups:
      - 'admins'
      - 'dev'
