watch:
  workers: 20
  schedule: "0 */6 * * *"
  firstCheckNotif: false
  runOnStartup: true

providers:
  docker:
    watchByDefault: true

notif:
  gotify:
    endpoint: http://gotify
    priority: 1
    timeout: 10s
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
