global:
  scrape_interval: 5s
  evaluation_interval: 15s
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "jellyfin"
    static_configs:
      - targets: ["jellyfin:8096"]
        labels:
          group: "jellyfin"
  - job_name: "searxng"
    static_configs:
      - targets: ["searxng:8080"]
        labels:
          group: "searxng"
    basic_auth:
      username: "doesnotmatter"
      password: "password"

  - job_name: "pinchflat"
    static_configs:
      - targets: ["pinchflat:8945"]
        labels:
          group: "pinchflat"
